replicaCount: 2

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "7"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: nginx.example.com
      paths:
        - /
  tls: []

